### PR TITLE
Fix account selection in account form

### LINKED ISSUE #832: Cannot reselect other account types when creating transactions
If you accidentally select a wrong account while entering transactions, Maffin doesn't let you reselect a new account, even after you close the transaction window and click [Add] again. 
Screenshot 2024-04-07 at 10 57 18 PM

### PR DESCRIPTION
**Pull request by argaen**
An old bug... passing an instance of a Split object makes the defaultValue reference to be updated when changing the value. Passing now a {} instead of a split instance in the add transaction second split to avoid this and then using `formState.defaultValues` to see if we have set a default for the account type.

Fixes #832

### CODE REVIEW

File: src/components/buttons/AddTxDropdown.tsx [hunk 1]
```diff
@@ -48,7 +48,10 @@ export default function AddTxDropdown({
                 {
                   date: (latestDate || DateTime.now()).toISODate() as string,
                   description: '',
-                  splits: [Split.create({ fk_account: account }), new Split()],
+                  splits: [
+                    Split.create({ fk_account: account }),
+                    {},
```
Comment (argaen) [inline src/components/buttons/AddTxDropdown.tsx:53]: passing a split object makes it that when we select an account for this split, the `defaultValues` object is also updated. Setting it to a raw object so this doesn't happen.

File: src/components/forms/transaction/SplitField.tsx [hunk 2]
```diff
@@ -69,6 +69,8 @@ export default function SplitField({
     form.trigger('splits');
   }, [value, exchangeRate, form, action, index]);
 
+  const defaultAccount = form.formState.defaultValues?.splits?.[index]?.fk_account as Account;
```
Comment (argaen) [inline src/components/forms/transaction/SplitField.tsx:72]: use the `formState.defaultValues` instead of account watcher to narrow user options.
